version: "3.9"

services:
  ml:
    container_name: summary_api
    restart: always
    build:
      context: .
      dockerfile: docker/ml/Dockerfile
    ports:
      - '80:3001'
    # environment:
    #   FLASK_DEBUG: "${FLASK_DEBUG:?}"
    networks:
      - app
    logging:
      driver: json-file
      options:
        max-size: 4m
        max-file: "1"